authentication/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'authentication'
urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^register/', views.register_user, name='register'),
    url(r'^register_success/', views.register_success),
    url(r'^confirm/(?P<activation_key>.+)$', views.register_confirm),
]

basket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.basket, name='basket'),
]

catalogue/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from catalogue.views import Catalogue
from catalogue.views import ProductsPage
from catalogue.views import FilteredProductsPage

app_name = 'catalogue'
urlpatterns = [
    url(r'^$', Catalogue.as_view(), name='catalog_main'),
    url(r'^(?P<category_slug>[\w-]+)_(?P<subcategory_slug>[\w-]+)$', ProductsPage.as_view(), name='products_page'),
    url(r'^(?P<category_slug>[\w-]+)_(?P<subcategory_slug>[\w-]+)/filter/(?P<extra_params>[\w\D]+)$', FilteredProductsPage.as_view(), name='filtered_products'),
]

go_fisher/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', include('startpage.urls')),
    url(r'^auth/', include('authentication.urls')),
    url(r'^basket/', include('basket.urls')),
    url(r'^catalog/', include('catalogue.urls')),
    url(r'^ordering/', include('ordering.urls')),
    url(r'^products/', include('product.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from product.views import Product_details

app_name = 'product'
urlpatterns = [
    url(r'^details/(?P<pk>\d+)/$', Product_details.as_view(), name='product_details'),
]

startpage/urls.py
from django.conf.urls import url
from startpage.views import IndexView

app_name = 'startpage'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name="home_page"),
]

catalogue/models.py
from django.db import models
import json
import unidecode
from unidecode import unidecode
from django.template.defaultfilters import slugify

class BigCategory(models.Model):
	name = models.CharField(max_length=30)
	def __str__(self):
		return self.name

class Category(models.Model):
	name = models.CharField(max_length=45)
	big_category = models.ForeignKey(BigCategory, default=1)
	slug = models.SlugField(default='')
	def __str__(self):
		return self.name

class Subcategory(models.Model):
	name = models.CharField(max_length=45)
	extra_parameters = models.TextField(null=True)
	image = models.FileField(upload_to = 'go_fisher/static/go_fisher/img/subcategories/', blank=False, null=True)
	slug = models.SlugField(default='')
	def __str__(self):
		return self.name
	def slice_ref(self):
		ref = str(self.image)
		i = ref.find('img/')
		return ref[i:len(ref)]
	def extra_to_dict(self):
		py_dict = json.loads(self.extra_parameters)
		return py_dict

product/models.py
from django.db import models
from decimal import Decimal
from catalogue.models import Subcategory, Category
import json
import re
import unidecode

class ProductFrom(models.Model):
	subcategory_id = models.ForeignKey(Subcategory, on_delete=models.PROTECT)
	category_id = models.ForeignKey(Category, on_delete=models.PROTECT)
	def __str__(self):
		return u'%s: %s - %s' % (self.category_id, self.subcategory_id, self.subcategory_id.extra_parameters)

class Image(models.Model):
	JPEG = 'JPEG'
	PNG = 'PNG'
	IMAGE_EXTENSION = (
		(JPEG, 'jpeg'),
		(PNG, 'png'),
		)
	name = models.CharField(max_length=60)
	extension = models.CharField(max_length=4,
							choices=IMAGE_EXTENSION,
							default=JPEG)
	image = models.FileField(upload_to = 'go_fisher/static/go_fisher/img/products', blank=False, null=True)
	def __str__(self):
		return self.name
	def slice_ref(self):
		ref = str(self.image)
		i = ref.find('img/')
		return ref[i:len(ref)]

class Special(models.Model):
	title = models.CharField(max_length=50)
	priority = models.IntegerField(blank=True, null=True)
	start_at = models.DateField()
	end_at = models.DateField()
	def __str__(self):
		return u'%s - %s - %s' % (self.title, self.start_at, self.end_at)

class Kind(models.Model):
	name = models.CharField(max_length=45)
	priority = models.IntegerField(blank=True, null=True)
	def __str__(self):
		return self.name

class Brand(models.Model):
	name = models.CharField(max_length=60)
	priority = models.IntegerField(blank=True, null=True)
	image = models.FileField(upload_to = 'go_fisher/static/go_fisher/img/brands', blank=False, null=True)
	def __str__(self):
		return self.name
	def slice_ref(self):
		ref = str(self.image)
		i = ref.find('img/')
		return ref[i:len(ref)]

class Product(models.Model):
	LENGTH = 'см'
	WEIGHT = 'гр'
	QUANTITY = 'шт'
	TYPE_OF_MEASUREMENTS = (
		(LENGTH, 'довжина'),
		(WEIGHT, 'вага'),
		(QUANTITY, 'кількість'),
		)
	title = models.CharField(max_length=50)
	description = models.TextField(null=True)
	image = models.ManyToManyField(Image, related_name='images')
	brand = models.ForeignKey(Brand, on_delete=models.PROTECT)
	model = models.CharField(max_length=50, null=True, blank=True)
	from_id = models.ForeignKey(ProductFrom, on_delete=models.PROTECT)
	kind = models.ManyToManyField(Kind)
	special = models.ManyToManyField(Special, null=True)
	price = models.DecimalField(max_digits=9, decimal_places=2, default=Decimal('0.00'))
	old_price = models.DecimalField(max_digits=9, decimal_places=2, default=Decimal('0.00'))
	create_at = models.DateField(auto_now=True, auto_now_add=False)
	quantity = models.PositiveSmallIntegerField()
	garanty = models.PositiveSmallIntegerField()
	priority = models.IntegerField(blank=True, null=True)
	is_best_offer = models.BooleanField()
	is_active = models.BooleanField()
	is_new = models.BooleanField()
	# value_mesure = models.PositiveSmallIntegerField()
	# measurer = models.CharField(max_length=2,
	# 						choices=TYPE_OF_MEASUREMENTS,
	# 						default=WEIGHT)
	extra_parameters_json = models.TextField(null=True)
	slug_params_json = models.TextField(blank=True, null=True)
	def __str__(self):
		return self.title
	# for creating sluged json-like field
	def save(self):
		extra_dict = json.loads(self.extra_parameters_json)
		slug_extra_list = []
		for key, value in extra_dict.items():
			uni_key = unidecode.unidecode(key).lower()
			sluged_key = re.sub(r'\W+', '-', uni_key)

			uni_value = unidecode.unidecode(value).lower()
			sluged_value = re.sub(r'\W+', '-', uni_value)

			slug_extra_list.append(sluged_key + '=' + sluged_value)
		self.slug_params_json = slug_extra_list
		super(Product, self).save()

	def extra_to_dict(self):
		py_dict = json.loads(self.extra_parameters_json)
		return py_dict

    #
	# def mesurer_name(self):
	# 	if self.measurer == 'см':
	# 		return 'Довжина'
	# 	elif self.measurer == 'гр':
	# 		return 'Вага'
	# 	elif self.measurer == 'шт':
	# 		return 'Кількість'

# clothe models
class Size(models.Model):
	size_name = models.CharField(max_length=10)
	def __str__(self):
		return self.name

class BrandClothe(models.Model):
	brand_name = models.SlugField(max_length=40)
	def __str__ (self):
		return self.brand_name

class Clothe(models.Model):
	title = models.SlugField(max_length=60)
	description = models.TextField()
	active = models.BooleanField()
	size = models.ForeignKey(Size, on_delete=models.PROTECT)
	brand = models.ForeignKey(BrandClothe, on_delete=models.PROTECT)
	image = models.FileField(upload_to = 'go_fisher/static/images/clothes', blank=False, null=True)
	def __str__(self):
		return self.title

catalogue/views.py
import operator
from functools import reduce
from django.db.models import Q

from django.views.generic import TemplateView
from django.views.generic import ListView
from catalogue.models import Category
from catalogue.models import Subcategory
from product.models import ProductFrom
from product.models import Product
from django.db.models import Max

class Catalogue(TemplateView):
    template_name = "catalogue.html"

    def get_context_data(self, **kwargs):
        context = super(Catalogue, self).get_context_data()
        context['category_list'] = Category.objects.all()
        context['subcategory_list'] = Subcategory.objects.all()
        context['comb_list'] = ProductFrom.objects.all()
        return context


class ProductsPage(ListView):
    model = Product
    template_name = "products_page.html"

    def get_context_data(self, **kwargs):
        context = super(ProductsPage, self).get_context_data()
        context['products'] = Product.objects.filter(from_id__subcategory_id__slug=self.kwargs['subcategory_slug'])
        context['max_price'] = str(Product.objects.filter(
            from_id__subcategory_id__slug=self.kwargs['subcategory_slug']).aggregate(Max('price'))['price__max']).split('.')[0]
        context['products_brands'] = Product.objects.filter(
            from_id__subcategory_id__slug=self.kwargs['subcategory_slug']). \
            order_by('brand__name').values_list('brand__name', flat=True).distinct()
        context['category'] = ProductFrom.objects.get(subcategory_id__slug=self.kwargs['subcategory_slug'])
        context['subcategories'] = ProductFrom.objects.all()
        context['extra_params'] = Subcategory.objects.get(slug=self.kwargs['subcategory_slug'])
        return context

class FilteredProductsPage(ListView):
    template_name = "products_page.html"

    def get_queryset(self, *args, **kwargs):
        extra = self.kwargs['extra_params']
        search_list = extra.split(';')
        brands = []

        if 'brand' in extra:
            # need re
            brand_partition = extra.partition('brand=')
            full_brand = brand_partition[1] + brand_partition[2].split(';')[0]
            brands = brand_partition[2].split(';')[0].split('_')
            # search params without brand
            search_list = [value for value in search_list if value != full_brand]

            # queryset = Product.objects.filter(brand__name=brands[0])
            queryset = Product.objects.filter(
                reduce(operator.or_, (Q(brand__name=x) for x in brands)))
            if search_list:
                queryset = queryset.filter(reduce(operator.and_, (Q(slug_params_json__contains=x) for x in search_list)))
            return queryset

        queryset = Product.objects.filter(reduce(operator.and_, (Q(slug_params_json__contains=x) for x in search_list)))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(FilteredProductsPage, self).get_context_data()
        context['products'] = self.get_queryset().filter(from_id__subcategory_id__slug=self.kwargs['subcategory_slug'])
        context['max_price'] = str(self.get_queryset().filter(
            from_id__subcategory_id__slug=self.kwargs['subcategory_slug']).aggregate(Max('price'))[
                                       'price__max']).split('.')[0]
        context['products_brands'] = self.get_queryset().filter(
            from_id__subcategory_id__slug=self.kwargs['subcategory_slug']). \
            order_by('brand__name').values_list('brand__name', flat=True).distinct()
        context['category'] = ProductFrom.objects.get(subcategory_id__slug=self.kwargs['subcategory_slug'])
        context['subcategories'] = ProductFrom.objects.all()
        context['extra_params'] = Subcategory.objects.get(slug=self.kwargs['subcategory_slug'])
        return context

product/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from product.models import Product

# Create your views here.

class Product_details(DetailView):
    context_object_name = 'product'
    template_name = 'product.html'
    # ??? do you really need it
    # queryset = Product.objects.all()

    def get_queryset(self):
        self.product = get_object_or_404(Product, pk=self.kwargs['pk'])
        return Product.objects.filter(pk=self.product.id)

    def get_context_data(self, **kwargs):
        context = super(Product_details, self).get_context_data()
        context['product'] = self.product
        context['kinds'] = Product.objects.get(pk=self.product.id).kind.all()
        context['images'] = Product.objects.get(pk=self.product.id).image.all()
        context['recommendations'] = Product.objects.all()[:3]
        context['popular'] = Product.objects.all()[:4]
        return context

templates/go_fisher/_catalogue_product.html
{% load staticfiles %}


<div class="col-sm-4 col-md-4 col-lg-3">
    <div class="item">
        <a href="{% url 'product:product_details' product.id %}" class="stock-a">
            <img src="{%  static product.image.first.slice_ref %}" alt="photo">
        </a>
        <a href="{% url 'product:product_details' product.id %}" class="stock-name">{{ product.title }}</a>
        <div class="info-row">
            <div class="price">{{ product.price }} грн.</div>
            <div class="brand"><img src="{%  static product.brand.slice_ref %}" alt="brand"></div>
        </div>
    </div>
</div>

templates/go_fisher/_footer.html
{% load staticfiles %}

<div class="container">
	<div class="row">
		<div class="social-networks ">
			<h2>Долучайтесь до нас в соц.мережах</h2>
			<a href=""><img src="{% static 'img/icons/fb.png' %}" alt="facebook"></a>
			<a href=""><img src="{% static 'img/icons/g+.png' %}" alt="google+"></a>
			<a href=""><img src="{% static 'img/icons/vk.png' %}" alt="vkontakte"></a>
			<a href=""><img src="{% static 'img/icons/twitter.png' %}" alt="twitter"></a>
		</div>
	</div>
	<div class="row">
		<div class="unit col-md-3 col-sm-4">
			<ul>
				<li><a href="">Гарантійні зобов’язання</a></li>
				<li><a href="">Каталог товарів</a></li>
				<li><a href="">Про компанію</a></li>
				<li><a href="">Контакти</a></li>
			</ul>		
		</div>
		<div class="footer-contacts col-md-4 col-sm-6">
				<p>м.Чернівці, вул. Калинівська 141 б</p>
				<div class="phone" style="background-image: url(img/phone.png);">(0 800) 502 181</div>
				<div class="phone" style="background-image: url(img/phone.png);">(0 800) 112 121</div>
				<div class="phone" style="background-image: url(img/mobile.png);">(066) 857 05 22</div>
				<div class="phone" style="background-image: url(img/mobile.png);">(066) 857 05 54</div>
		</div>
	</div>

</div>

templates/go_fisher/_header.html
{% load staticfiles %}

<div class="pre-topline">
	<div class="container">
		<div class="col-md-push-6 col-md-6">
			<div class="contacts">
				<div class="phone" style="background-image: url({% static 'img/phone.png' %});">(0 800) 502 181</div>
				<div class="phone" style="background-image: url({% static 'img/mobile.png' %});">(066) 857 05 22</div>
				<div class="callback" style="background-image: url({% static 'img/callback.png' %});">Замовити дзвінок</div>
			</div>
		</div>
	</div>
</div>

<div class="top-line">
	<div class="container">
		<div class="row">
			<div class="col-sm-1 hidden-lg hidden-md col-xs-1">
				<div class="mobile-mnu">
					<div class="toggle-mnu hidden-lg"><span></span></div>
				</div>
			</div>

			<div class="mobile-search col-sm-2 hidden-lg hidden-md col-xs-2">
				<img src="{% static 'img/mobile-search.png' %}" alt="search" class="m-search" width="35" height="35"/>
			</div>
			
			<div class="col-md-4 col-lg-3 col-sm-5 col-xs-3">
				<div class="logo">
					<a href="/"><img src="{% static 'img/logo.png' %}" alt="Рибалка"></a>		
					</div>
			</div>
			<div class="col-md-5 col-lg-6 col-sm-4 hidden-sm hidden-xs ">
				<form class="form-wrapper">
					<div class="search">
						<input type="text" placeholder="Пошук товарів">
						<!-- !!!! -->
						<button type="submit"><a href="/" class="icon-find">
							<img src="{% static 'img/serch.png' %}" alt=""></a>
						</button>
					</div>
				</form>
			</div>
			<div class="col-md-3 col-lg-3 col-sm-4 col-xs-5">
				
				<a href="/" class="basket">
					<div class="counter">4</div>
					<img src="{% static 'img/basket2.png' %}" alt="basket" /></a>
					<div class="enter" style="background-image: url({% static 'img/icons/enter.png' %});">
					<a href="{% url 'authentication:login' %}">Увійти</a>
				</div>
			</div>
		</div>
	</div>
</div>

templates/go_fisher/_menu.html
<div class="container">
	<div class="col-md-12">
		<ul>
            {% url 'startpage:home_page' as url %}
            <li {% if request.path == url %} class="active" {% endif %} >
                <a href="{{ url }}">Головна</a>
            </li>
            {% url 'catalogue:catalog_main' as url %}
            <li {% if url in request.path %} class="active" {% endif %} >
                <a href="{{ url }}">Каталог</a>
            </li>
			<li>
                <a href="">Акції</a>
            </li>
			<li>
                <a href="">Сервіс</a>
            </li>
			<li>
                <a href="">Контакти</a>
            </li>
		</ul>
	</div>
</div>

templates/go_fisher/_mob_menu.html
<div class="sidebar">
    <ul>
        <li><a href="#">Головна</a></li>
        <li><a href="#">Каталог</a></li>
        <li><a href="#">Сервіс</a></li>
        <li><a href="#">Контакти</a></li>
        <li><a class="exit" href="#">Х-Вихід</a></li>
    </ul>
</div>

templates/go_fisher/index.html
{% extends "__base.html" %}
{% load staticfiles %}

{% block main_style %}
    <link rel="stylesheet" href="{% static 'css/_main.min.css' %}">
{% endblock %}

{% block content %}
	<div class="baner-section" style="background-image: url({% static 'img/img-5.jpg' %}); ">
		<div class="col-md-10 col-md-push-1 col-sm-10 col-sm-push-1 hidden-xs wpr-baner">
			<div class="col-md-8 col-md-push-2 col-sm-8 col-sm-push-2 baner">
				<ul>
					<li class="resp-w-item">
						<div class="item">
							<div class="img-wp col-md-5 col-sm-5">
								<img src="{% static 'img/goods/loo.png' %}" alt="">
							</div>
							<div class="info-details col-md-7 col-sm-7">
								<h1>Знижка <span>- 25%</span></h1>
								<h2>на всі котушки фірми <b>Mikado</b></h2>
								<h3>Пропозиція діє до <span>30.05</span></h3>
								<a href="/">Переглянути</a>
							</div>
						</div>
					</li>
					<li class="resp-w-item">
						<div class="item">
							<div class="img-wp col-md-5 col-sm-5">
								<img src="{% static 'img/goods/loo.png' %}" alt="">
							</div>
							<div class="info-details col-md-7 col-sm-7">
								<h1>Знижка <span>- 26%</span></h1>
								<h2>на всі котушки фірми <b>Mikado</b></h2>
								<h3>Пропозиція діє до <span>30.05</span></h3>
								<a href="/">Переглянути</a>
							</div>
						</div>
					</li>
					<li class="resp-w-item">
						<div class="item">
							<div class="img-wp col-md-5 col-sm-5">
								<img src="{% static 'img/goods/loo.png' %}" alt="">
							</div>
							<div class="info-details col-md-7 col-sm-7">
								<h1>Знижка <span>- 27%</span></h1>
								<h2>на всі котушки фірми <b>Mikado</b></h2>
								<h3>Пропозиція діє до <span>30.05</span></h3>
								<a href="/">Переглянути</a>
							</div>
						</div>
					</li>
											
				</ul>
			</div>
			<div class="slider-nav">
				<button data-dir="prev" class="l-arrow"></button>
				<button data-dir="next" class="r-arrow"></button>
			</div>
		</div>
	</div>
	<div class="categories">
		<div class="container">
			<div class="row">
				<div class="category-title">Відбір по категорії</div>
                {% for bigcategory in home_list %}
                    <div class="subcategory-section col-md-3 col-sm-3 col-lg-3 col-xs-5">
                        <div class="subcategory-item">
                            <div class="subc-a">
                                {% with i=forloop.counter|stringformat:"s" %}
                                    {% with 'img/categories/fish-part-'|add:i|add:'.png' as big_cat_src %}
                                        <img src="{% static big_cat_src %}" alt="category">
                                    {% endwith %}
                                {% endwith %}
                            </div>

                            <p class="subc-name">{{ bigcategory.name }}</p>

                            {% for category in category_list %}
                                {% if category.big_category == bigcategory %}
                                    <a href="/" class="subc-s-item">{{ category.name }}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
			</div>
		</div>
	</div>
    <div class="kinds">
        <div class="container">
            <div class="row">
                <div class="kind-title col-md-12 col-lg-12 col-sm-12">Відбір за призначенням</div>
                    <div class="kind-section col-lg-12 col-md-12">
                        <div class="kind">
                            {% for kind in kind_list %}
                                <figure class="subkind-item">
                                    {% with i=forloop.counter|stringformat:"s" %}
                                        {% with 'img/kinds/kind-'|add:i|add:'.png' as image_src %}
                                            <a href="/" class="subk-a"><img src="{% static image_src %}" alt="kind"></a>
                                        {% endwith %}
                                    {% endwith %}
                                    <figcaption><a href="/" class="subk-name">{{ kind.name }}</a></figcaption>
                                </figure>
                            {% endfor %}
                        </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="capital-stock">
        <div class="container">
            <div class="row">
                <div class="stock-title">Акції</div>
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' with hidden='hidden-sm' %}
            </div>
        </div>
    </div>
    <div class="new">
        <div class="container">
            <div class="row">
                <div class="stock-title">Новинки</div>
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' with hidden='hidden-sm'%}
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' with hidden='hidden-sm'%}
            </div>
        </div>
    </div>
    <div class="popular">
        <div class="container">
            <div class="row">
                <div class="stock-title">Популярні товари</div>
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' %}
                {% include '_product.html' with hidden='hidden-sm' %}
            </div>
        </div>
    </div>
{% endblock %}

{% block rel_scripts %}
<script type="text/javascript" src="{%  static 'js/slider.js'%}"></script>

<script>
	(function() {
		var container = $('div.baner').children('ul');
		var slider = new Slider( container, $('.slider-nav') );

		slider.nav.find('button').on('click', function() {
			slider.setCurrent( $(this).data('dir') );
			slider.transition();
		});

		//define slider behavior after resizing the window
		$(window).resize(function() {
			var cur_item_width = $(".baner").width();
			$(".resp-w-item").css('width', cur_item_width);
			slider.resize_transition();
		})
	})();
</script>

{% endblock %}

templates/go_fisher/products_page.html
{% extends "__base.html" %}
{% load staticfiles %}
{% load catalogue_filters %}

{% block main_style %}
    <link rel="stylesheet" href="{% static 'css/_products_page.min.css' %}">
{% endblock %}

{% block content %}

	<div class="wpr">

		<div class="container">
			<div class="row">
				<ul class="breadcrumb">
					<li><a href="#">Головна</a></li>
					<li><a href="#">Каталог</a></li>
					<li class="active">Вудилища</li>
				</ul>
				<div class="filter-btn hidden-lg hidden-md">Фільтр</div>
			</div>
			<div class="col-md-3 col-sm-12">
				<div class="filter">
					<div class="part">
                        <div class="title">{{ category.category_id }}</div>
                        <ul>
                            {% for subcategory in subcategories %}
                                {% if subcategory.category_id == category.category_id %}
                                    <li><a href="{% url 'catalogue:products_page' category.category_id.slug subcategory.subcategory_id.slug %}"
                                        {% if subcategory.subcategory_id.slug in request.path|partition_url %} class="active" {% endif %}>{{ subcategory.subcategory_id }}</a></li>
                                {% endif %}
                            {% endfor %}
						</ul>
					</div>

                    {% if products %}
                        <form class="advance_search" method="GET" >
                            <div class="title">Фільтр товарів</div>
                            {% with request.path as cur_url %}
                                <div class="price col-md-12 col-sm-3">
                                    <div class="sect-title">Ціна</div>
                                    <div class="value">
                                        від
                                        <input type="number" name="from_price" value="0" min="0" max="{{ max_price }}"><br/>
                                        до &nbsp;<input type="number" name="to_price" value="{{ max_price }}" min="0" max="{{ max_price }}">
                                        </div>
                                    </div>
                                <div class="companies col-md-12 col-sm-4">
                                    <div class="sect-title">Бренд</div>
                                    <div class="comp-wrapper">
                                        {% for product_brand in products_brands %}
                                            {% create_full_param 'brand'|ctm_slugify product_brand|ctm_slugify as sluged_new_item %}
                                                <a href="{{ cur_url|check_right_url:sluged_new_item }}" class="filter-item">{{ product_brand }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                                {% for key, value in extra_params.extra_to_dict.items %}
                                    <div class="col-md-12 col-sm-4">
                                        <div class="sect-title">{{ key }}</div>
                                        <div class="extra-params-wrapper">
                                            {% for parameter in value|split_by:'/' %}
                                                {% create_full_param key|ctm_slugify parameter|ctm_slugify as sluged_new_item %}
                                                    <a href="{{ cur_url|check_right_url:sluged_new_item}}" class="filter-item">{{ parameter }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endwith %}
                        </form>
                    {% endif %}
                    <div class="clear"></div>
                </div>
			</div>

			<div class="col-md-9 col-sm-12">
				<div class="overview-wrp unique">
					{% for product in products %}
                        {% include '_catalogue_product.html' with product=product %}
                    {% empty %}
                        <h4>Обрана категорія поки що порожня</h4>
                    {% endfor %}
				</div>
			</div>

			<div class="clear"></div>
			<div class="col-sm-12">	
				<div class="paging-wpr">
					<ul class="pagination">
						<li>
							<a href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
						<li class="active"><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
							<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{#{% block rel_scripts %}#}
{#<script type="text/javascript" src="{%  static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>#}
{##}
{#<script>#}
{#    (function(){#}
{#        $(window).on("load", function(){#}
{#            $(".comp-wrapper").mCustomScrollbar();#}
{#            $(".extra-params-wrapper").mCustomScrollbar();#}
{#        });#}
{#    })();#}
{#</script>#}
{#{% endblock %}#}